# SwiftLint Configuration for RecipeFinder

# Paths to include/exclude
included:
  - RecipeFinder
  
excluded:
  - Pods
  - RecipeFinder.xcodeproj
  - RecipeFinder.xcworkspace
  - DerivedData
  - .build
  - docs
  - Assets.xcassets

# Rules
disabled_rules:
  - trailing_whitespace # Too strict for development
  - todo # Allow TODO comments during development
  
opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - force_unwrapping # Warn on force unwrapping
  - multiline_parameters
  - sorted_imports
  
# Rule configurations
line_length:
  warning: 150
  error: 200
  ignores_comments: true
  ignores_urls: true
  
file_length:
  warning: 500
  error: 1000
  
function_body_length:
  warning: 50
  error: 100
  
type_body_length:
  warning: 300
  error: 500
  
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - URL
    - x
    - y
    - _name # Core Data generated property
    
cyclomatic_complexity:
  warning: 15
  error: 25
  
nesting:
  type_level:
    warning: 2

# Custom rules
custom_rules:
  no_print:
    name: "No Print Statements"
    regex: '^\s*print\('
    message: "Use debugLog() instead of print() for release builds"
    severity: warning
    
  force_cast:
    name: "Force Cast"
    regex: 'as!'
    message: "Avoid force casting. Use optional casting (as?) instead"
    severity: warning

# Analyzer rules (requires full build)
analyzer_rules:
  - unused_declaration
  - unused_import

# Reporter
reporter: "xcode"
