name: Build iOS App

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  SCHEME: RecipeFinder
  CONFIGURATION: Debug
  DESTINATION: 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.5'

jobs:
  build:
    name: 🔨 Build
    runs-on: macos-14
    timeout-minutes: 30
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Select Xcode version
        run: |
          if [ -d "/Applications/Xcode_15.4.app" ]; then
            sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer
          elif [ -d "/Applications/Xcode_15.3.app" ]; then
            sudo xcode-select -s /Applications/Xcode_15.3.app/Contents/Developer
          else
            sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
          fi
      
      - name: Show Xcode version
        run: xcodebuild -version
      
      - name: Clean Package.resolved if exists
        run: |
          RESOLVED_FILE="RecipeFinder.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved"
          if [ -f "$RESOLVED_FILE" ]; then
            echo "Removing Package.resolved..."
            rm -f "$RESOLVED_FILE"
          fi
      
      - name: Build project
        run: |
          xcodebuild build \
            -scheme ${{ env.SCHEME }} \
            -destination '${{ env.DESTINATION }}' \
            -configuration ${{ env.CONFIGURATION }} \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

  summary:
    name: 📊 Summary
    runs-on: macos-14
    timeout-minutes: 5
    needs: [build]
    if: always()
    
    steps:
      - name: Generate summary
        run: |
          echo "## 🎉 Build Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Job | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-----|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| 🔨 Build | ${{ needs.build.result }} |" >> $GITHUB_STEP_SUMMARY
