name: iOS CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

# Prevent multiple workflow runs for the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-14
    timeout-minutes: 30
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer
      
    - name: Show Xcode version
      run: xcodebuild -version
      
    - name: Show available simulators
      run: xcrun simctl list devices available
      
    - name: Cache SPM dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/Library/Caches/org.swift.swiftpm
          .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    
    - name: Cache DerivedData
      uses: actions/cache@v4
      with:
        path: DerivedData
        key: ${{ runner.os }}-deriveddata-${{ hashFiles('**/*.swift') }}
        restore-keys: |
          ${{ runner.os }}-deriveddata-
    
    - name: Install dependencies
      run: |
        xcodebuild -resolvePackageDependencies -scheme RecipeFinder
    
    - name: Build for testing
      run: |
        xcodebuild build-for-testing \
          -scheme RecipeFinder \
          -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.2' \
          -configuration Debug \
          -derivedDataPath DerivedData \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
    
    - name: Run tests
      run: |
        xcodebuild test-without-building \
          -scheme RecipeFinder \
          -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.2' \
          -configuration Debug \
          -derivedDataPath DerivedData \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          -resultBundlePath TestResults.xcresult
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: TestResults.xcresult
        retention-days: 7

  release-build:
    name: Release Build
    runs-on: macos-14
    timeout-minutes: 30
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [build-and-test, code-quality, security-scan]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer
    
    - name: Cache SPM dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/Library/Caches/org.swift.swiftpm
          .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    
    - name: Build Release
      run: |
        xcodebuild build \
          -scheme RecipeFinder \
          -destination 'generic/platform=iOS' \
          -configuration Release \
          -derivedDataPath DerivedData \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
    
    - name: Archive app
      run: |
        xcodebuild archive \
          -scheme RecipeFinder \
          -archivePath RecipeFinder.xcarchive \
          -configuration Release \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO || echo "Archive step skipped (requires signing)"

  code-quality:
    name: Code Quality Checks
    runs-on: macos-14
    timeout-minutes: 15
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer
    
    - name: Cache SwiftLint
      uses: actions/cache@v4
      with:
        path: /usr/local/bin/swiftlint
        key: ${{ runner.os }}-swiftlint-${{ hashFiles('.swiftlint.yml') }}
        restore-keys: |
          ${{ runner.os }}-swiftlint-
    
    - name: SwiftLint
      run: |
        # Install SwiftLint if not present
        if ! command -v swiftlint &> /dev/null; then
          brew install swiftlint
        fi
        
        # Run SwiftLint
        swiftlint lint --reporter github-actions-logging
    
    - name: Check for TODO/FIXME
      run: |
        echo "🔍 Checking for TODO/FIXME comments..."
        grep -r "TODO\|FIXME" RecipeFinder --include="*.swift" || echo "✅ No TODO/FIXME found"
      continue-on-error: true

  security-scan:
    name: Security Scan
    runs-on: macos-14
    timeout-minutes: 10
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Check for sensitive data
      run: |
        echo "🔒 Scanning for potential sensitive data..."
        
        FOUND_ISSUES=0
        
        # Check for API keys
        if grep -r "api_key\|apiKey\|API_KEY" RecipeFinder --include="*.swift" --exclude="*Test*.swift"; then
          echo "⚠️ Potential API keys found"
          FOUND_ISSUES=1
        else
          echo "✅ No API keys detected"
        fi
        
        # Check for passwords (excluding comments)
        if grep -r "password\|passwd\|pwd" RecipeFinder --include="*.swift" --exclude="*Test*.swift" | grep -v "//"; then
          echo "⚠️ Potential passwords found"
          FOUND_ISSUES=1
        else
          echo "✅ No passwords detected"
        fi
        
        # Check for private keys
        if grep -r "private_key\|privateKey\|PRIVATE_KEY" RecipeFinder --include="*.swift" --exclude="*Test*.swift"; then
          echo "⚠️ Potential private keys found"
          FOUND_ISSUES=1
        else
          echo "✅ No private keys detected"
        fi
        
        if [ $FOUND_ISSUES -eq 1 ]; then
          echo "❌ Security issues found! Please remove sensitive data from source code."
          exit 1
        fi

  documentation:
    name: Documentation Check
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Check documentation
      run: |
        echo "📚 Checking documentation..."
        
        # Check for README
        if [ -f "readme.md" ] || [ -f "README.md" ]; then
          echo "✅ README found"
        else
          echo "❌ README missing"
          exit 1
        fi
        
        # Check for DOCUMENTATION
        if [ -f "DOCUMENTATION.md" ]; then
          echo "✅ DOCUMENTATION.md found"
        else
          echo "⚠️ DOCUMENTATION.md missing"
        fi
        
        # Check for LICENSE
        if [ -f "LICENSE" ]; then
          echo "✅ LICENSE found"
        else
          echo "⚠️ LICENSE missing"
        fi

  notification:
    name: Build Status Notification
    needs: [build-and-test, code-quality, security-scan, documentation]
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: Check build status
      run: |
        echo "📊 Build Status Summary:"
        echo "  Build & Test: ${{ needs.build-and-test.result }}"
        echo "  Code Quality: ${{ needs.code-quality.result }}"
        echo "  Security Scan: ${{ needs.security-scan.result }}"
        echo "  Documentation: ${{ needs.documentation.result }}"
        
        # Only fail if critical jobs failed
        if [ "${{ needs.build-and-test.result }}" == "failure" ] || \
           [ "${{ needs.code-quality.result }}" == "failure" ] || \
           [ "${{ needs.security-scan.result }}" == "failure" ]; then
          echo "❌ Critical checks failed!"
          exit 1
        fi
        
        echo "✅ All checks passed!"
