name: Swift Lint & Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    name: Lint & Test
    runs-on: macos-14
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer
      
    - name: Show Xcode version
      run: xcodebuild -version
      
    - name: Install SwiftLint
      run: brew install swiftlint
      
    - name: Run SwiftLint
      run: swiftlint lint RecipeFinder/ --config .swiftlint.yml --strict
      
    - name: Build project
      run: |
        xcodebuild build \
          -scheme RecipeFinder \
          -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.2' \
          CODE_SIGNING_ALLOWED=NO
      
    - name: Run tests
      run: |
        xcodebuild test \
          -scheme RecipeFinder \
          -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.2' \
          CODE_SIGNING_ALLOWED=NO
